Repository ahmedeid6842/catalog-of-my-things, pull requests merged in 2023-09, with the labels that each got.

#41 Ruby group capstone: Catalog of my things - Project Setup
  .github/workflows/linters.yml
  .rubocop.yml
  GemFile
  Gemfile.lock
  app.rb
  lib/controllers/menu_controller.rb
  lib/item.rb
  main.rb
Labels: enhancement

#42 Milestone: Implement Game & Author classes' constructors and properties.
  lib/classes/author.rb
  lib/classes/game.rb
  lib/item.rb
Labels: enhancement, Game, Author

#44 Implement `add_item` and `can_be_archived` methods :rocket:
  lib/classes/author.rb
  lib/classes/game.rb
Labels: Game, Author

#45 Add unit tests for all implemented methods at `Author` & `Game` classes. :test_tube:
  lib/classes/game.rb
  lib/item.rb
  spec/author_spec.rb
  spec/game_spec.rb
Labels: Game, Author

#47 catalog-of-my-things: Feature/book and label
  lib/classes/label.rb
  lib/data/labels.json
  spec/label_spec.rb
Labels: enhancement, Label

#48 Implement the controllers of `Game` and `Author` :video_game: :fire:
  app.rb
  lib/helpers/data_manager.rb
  lib/item.rb
Labels: Game, Author

#50 Feature/preserve book label data
  app.rb
  lib/classes/label.rb
  lib/data/books.json
  lib/data/labels.json
  lib/helpers/data_manager.rb
  lib/helpers/list_manager.rb
  lib/item.rb
Labels: enhancement, Book, Label

#51 Implement the database schema for the `Author` and `Game` tables :100: :floppy_disk:
  schema.sql
Labels: Game, Author

#53 Add book and label tables
  schema.sql
Labels: enhancement, Book, Label

#56 Final touches :ok_hand:
  app.rb
  lib/controllers/menu_controller.rb
  main.rb
Labels: enhancement

#55 Capstone Ruby (Catalog of my things) 👌:rocket:
  .github/workflows/linters.yml
  .rspec
  .rubocop.yml
  GemFile
  Gemfile.lock
  LICENSE
  README.md
  app.rb
  lib/classes/author.rb
  lib/classes/game.rb
  lib/classes/genre.rb
  lib/classes/label.rb
  lib/classes/musicalbum.rb
  lib/controllers/menu_controller.rb
  lib/helpers/data_manager.rb
  lib/item.rb
  lib/models/book.rb
  lib/records/items.json
  main.rb
  schema.sql
  spec/author_spec.rb
  spec/book_spec.rb
  spec/game_spec.rb
  spec/genre_spec.rb
  spec/label_spec.rb
  spec/musicalbum_spec.rb
  spec/spec_helper.rb
Labels: documentation, enhancement
